version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
      - public_portfolio:/app/public # Named volume

volumes:
  public_portfolio: # Define the 'public' volume

networks:
  dokploy-networks:
    external: true
