version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - /app/node_modules
      - public_portfolio:/app/public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`dynodhan.xyz`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

volumes:
  public_portfolio:

networks:
  dokploy-networks:
    external: true
